FROM openjdk:7-jdk

# Download hadoop
RUN wget -qO- http://mirror.dkd.de/apache/hadoop/common/hadoop-2.9.0/hadoop-2.9.0.tar.gz | tar xz -C /opt

RUN apt-get update && apt-get install -y ssh rsync vim

# Passphraseless SSH
RUN ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa && \
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
    chmod 0600 ~/.ssh/authorized_keys

EXPOSE 50070

#ENV JAVA_HOME /usr/bin/java
ENV PATH="/opt/hadoop-2.9.0/bin:${PATH}"
